molecule-test:
	molecule test
molecule-verify:
	molecule verify
molecule-create:
	molecule create
molecule-converge:
	molecule converge
molecule-destroy:
	molecule destroy
molecule-idempotence:
	molecule idempotence
molecule-list:
	molecule list
