dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:latest
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
scenario:
  name: default
